#pragma once

enum returnCodes {
    SUCCESS = 0,
    PRINT_HELP = 3,
    ERR_NO_ARGS,
    ERR_ARG,
    ERR_UNKNOWN_COMMAND,
    ERR_BUILDING_STRING,
    ERR_HOST_NOT_RESOLVED,
    ERR_SOCKET_ERROR,
    ERR_SERVER_CONNECTION,
    ERR_SEND_UNSUCCESSFUL,
    ERR_RECV_UNSUCCESSFUL,
    ERR_INCORRECT_OUTPUT
};
